---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      MD029:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
  - "bin/**/*"
exclude_paths:
  - Procfile
  - LICENSE
  - "**.ejs"
  - "**.yml"
  - "**.opts"
